FROM python:3.10-slim

RUN pip install --no-cache-dir \
    "scanpy>=1.10" \
    "pyro-ppl>=1.9.1" \
    hmmlearn \
    leidenalg \
    python-igraph \
    seaborn \
    scikit-learn \
    "sc-echidna>=1.0.3"
